\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Assignment 3 - Solution},
            pdfauthor={Sanja Stanisic, n. 800409},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Assignment 3 - Solution}
\author{Sanja Stanisic, n. 800409}
\date{26 May 2020}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{5}
\tableofcontents
}
\hypertarget{problem-1}{%
\subsection{Problem 1}\label{problem-1}}

Using the bisection method calculate at least one zero for
\[f(x)=−x^3+4x^2−2\] starting for a suitable initial guess. You may want
to reuse the code provided in the exercise session.

\hypertarget{solution-1}{%
\subsubsection{Solution 1}\label{solution-1}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(NLRoot)}

\NormalTok{func <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) \{}
  \KeywordTok{return}\NormalTok{ (−x}\OperatorTok{^}\DecValTok{3}\OperatorTok{+}\DecValTok{4}\OperatorTok{*}\NormalTok{x}\OperatorTok{^}\NormalTok{2−}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}

\KeywordTok{curve}\NormalTok{(func, }\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{lwd=}\FloatTok{1.5}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{h=}\DecValTok{0}\NormalTok{)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{800409_SanjaStanisic_Assignment3_files/figure-latex/unnamed-chunk-1-1.pdf}

As the graph shows there are two roots of the equation
\[f(x)=−x^3+4x^2−2 = 0\] Therefore, we can apply the bisection method on
two intervals: \([-1,0]\) and \([0,1]\).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{BFfzero}\NormalTok{(func, }\DecValTok{-1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
## [1] -0.6554413
## [1] -7.168402e-06
## [1] "finding root is successful"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{BFfzero}\NormalTok{(func, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
## [1] 0.7892426
## [1] -6.958254e-06
## [1] "finding root is successful"
\end{verbatim}

The solution in the interval \([-1,0]\) is \(-0.6554413\), and
\(0.7892426\) in the interval \([0,1]\).

If we want to find roots of the equation and not use the library
\emph{NLRoot}, we can do as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bisection <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(f, a, b, }\DataTypeTok{n =} \DecValTok{1000}\NormalTok{, }\DataTypeTok{tol =} \FloatTok{1e-7}\NormalTok{) \{}
    \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{sign}\NormalTok{(}\KeywordTok{f}\NormalTok{(a) }\OperatorTok{==}\StringTok{ }\KeywordTok{sign}\NormalTok{(}\KeywordTok{f}\NormalTok{(b)))) \{}
    \KeywordTok{stop}\NormalTok{(}\StringTok{'signs of f(a) and f(b) must differ'}\NormalTok{)}
\NormalTok{  \}}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\NormalTok{n) \{}
\NormalTok{    c <-}\StringTok{ }\NormalTok{(a }\OperatorTok{+}\StringTok{ }\NormalTok{b) }\OperatorTok{/}\StringTok{ }\DecValTok{2} \CommentTok{# Calculate midpoint}
    \ControlFlowTok{if}\NormalTok{ ((}\KeywordTok{f}\NormalTok{(c) }\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{) }\OperatorTok{||}\StringTok{ }\NormalTok{((b }\OperatorTok{-}\StringTok{ }\NormalTok{a) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{) }\OperatorTok{<}\StringTok{ }\NormalTok{tol) \{}
      \KeywordTok{return}\NormalTok{(c)}
\NormalTok{    \}}
    
    \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{sign}\NormalTok{(}\KeywordTok{f}\NormalTok{(c)) }\OperatorTok{==}\StringTok{ }\KeywordTok{sign}\NormalTok{(}\KeywordTok{f}\NormalTok{(a)))\{}
\NormalTok{           a <-}\StringTok{ }\NormalTok{c}
\NormalTok{    \}}
    \ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{      b <-}\StringTok{ }\NormalTok{c}
\NormalTok{    \}       }
\NormalTok{  \}}
  \KeywordTok{print}\NormalTok{(}\StringTok{'Too many iterations'}\NormalTok{)}
\NormalTok{\}}

\KeywordTok{bisection}\NormalTok{(func, }\DecValTok{-1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.6554424
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{bisection}\NormalTok{ (func, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7892441
\end{verbatim}

The obtained solutions are equal to those obtained by using the
\emph{NLRoot} library.

\hypertarget{problem-2}{%
\subsection{Problem 2}\label{problem-2}}

Consider the following minimization problem:
\[min \  f(x1,x2)=2x_1^2+x_1x_2+2(x_2−3)^2\].

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Apply an iteration of the gradient method by performing the line
  search in an exact way, starting from the point A=(−1,4)⊤. Report all
  the steps of the method, not just the result.
\item
  Apply an iteration of Newton's method from point A. Verify that the
  point found is the minimum of function f. Report all the steps of the
  method, not just the result.
\item
  How many iterations of Newton's method are required to optimize a
  quadratic function?
\end{enumerate}

\hypertarget{solution-2.1}{%
\subsubsection{Solution 2.1}\label{solution-2.1}}

Since \[f(x1,x2)=2x_1^2+x_1x_2+2(x_2−3)^2\]

then \[ \nabla f(x_1, x_2) = [4x_1+x_2, x_1+4(x_2-3)]\]

\(x_0 = (-1,4)^T\)

\(f(x_0) = 2-4+2=0\)

Since we are minimizing the function, the search vector is negative:

\[d_0 = - \nabla f(x_0) \\
d_0 = -[4(-1)+4, -1+4(4-3)]\\
d_0 = -[0,3]\]

The next point is calculated as follows:

\[ x_1 = x_0 + \alpha_0 d_0\]
\[f(x_1) = f (x_0 + \alpha_0 d_0) = f ( \left[
\begin{array}
{c}
-1 \\
4 
\end{array}\right] +
\alpha_0 \left[ \begin{array}
{c}
0 \\
-3 
\end{array}\right] 
) = f(\left[
\begin{array}
{c}
-1 \\
4-3\alpha_0
\end{array}\right]) \]

\[f(x_1) = 2(-1)^2 + (-1)(4-3\alpha_0) +2(4-3\alpha_0-3)^2 = 2 + (3\alpha_0 - 4) + 2(1-3\alpha_0)^2\]

We set \[\frac {df(x_1)} {d\alpha_0} = 0\] and solve for \(\alpha_0\)
using a single-variable solution method.
\[\frac{df(x_1)} {d\alpha_0} =  3+4(1-3\alpha_0)(-3)\]
\[\frac {df(x_1)} {d\alpha_0} = 3-12+36\alpha_0 = 0\]
\[36 \alpha_0 -9 = 0\] \[\alpha_0 = \frac {9}  {36} = \frac {1}  {4}\]
\[x_1 = x_0 + \alpha_0 d_0 =  \left[
\begin{array}
{c}
-1 \\
4 
\end{array}\right] +
\frac{1}{4} \left[
\begin{array}
{c}
0 \\
3 
\end{array}\right] = \left[
\begin{array}
{c}-1 \\
\frac{13}{4}
\end{array}\right]\]

At this point the fulfillment of a stop criterium is checked:
\[|f(x_1) - f(x_0)| < \epsilon \]

\end{document}
